version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t demoapp:latest .
      - docker tag demoapp:latest 8809312967587.dkr.ecr.us-east-1.amazonaws.com/demorep:latest
  post_build:
    commands:
      - docker push 809312967587.dkr.ecr.us-east-1.amazonaws.com/demorep:latest
      - printf '[{"demoapp,"imageUri":"%s"}]' 809312967587.dkr.ecr.us-east-1.amazonaws.com/demorep > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
